<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL5jdjmh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL5jdjmh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerL5jdjmh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerL5jdjmh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerL5jdjmh\appProdProjectContainer([
    'container.build_hash' => 'L5jdjmh',
    'container.build_id' => 'd6781058',
    'container.build_time' => 1583085341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL5jdjmh');
