<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.user_checker' shared autowired service.

return $this->services['app.user_checker'] = new \UserBundle\Security\UserChecker();
