<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.yui_js' shared service.

$this->services['assetic.filter.yui_js'] = $instance = new \Assetic\Filter\Yui\JsCompressorFilter(($this->targetDirs[3].'\\app/Resources/java/yuicompressor.jar'), 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath\\java.EXE');

$instance->setCharset('UTF-8');
$instance->setTimeout(NULL);
$instance->setStackSize(NULL);
$instance->setNomunge(NULL);
$instance->setPreserveSemi(NULL);
$instance->setDisableOptimizations(NULL);
$instance->setLineBreak(NULL);

return $instance;
