<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'upload_service' shared autowired service.

return $this->services['upload_service'] = new \MainBundle\Service\UploadService();
